config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'
  resources :leagues do
    resources :seasons do
      resources :games do
        resources :players do
          resource :finish, only: [:update]
        end
        resource :game_over, only: [:update]
      end
      resource :activate, only: [:update]
      resource :complete, only: [:update]
    end
  end
end

app/models/league.rb
class League < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  has_many :permissions, -> { where(subject_class: 'League') }, foreign_key: :subject_id, dependent: :destroy
  has_many :seasons, dependent: :destroy
	has_many :games, through: :seasons
  has_many :players, through: :games

  delegate :permissions, to: :creator, prefix: true, allow_nil: false
  delegate :full_name, to: :creator, prefix: true, allow_nil: false

  validates :user_id, presence: true
  validates :name, presence: true, uniqueness: true

  after_create_commit :create_permission, :create_initial_season

  def active_season
    seasons.where(active: true).first
  end

  def active_season_standings(season=nil)
    season = season || active_season || Season.last
    season.players_rankings
  end

  private

  def create_initial_season
    self.seasons.create(active: true, completed: false)
  end

  def create_permission
    creator_permissions.create!(subject_id: self.id, subject_class: self.class.to_s, action: 'manage')
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  load_and_authorize_resource :league, through: :current_user, except: [:show]

  def index
  end

  def show
    @league = League.find(params[:id])
    @standings = @league.active_season_standings
  end

  def new
  end

  def edit
  end

  def create
    if @league.save
      redirect_to @league
    else
      render :new
    end
  end

  def update
    if @league.update(league_params)
      redirect_to @league
    else
      render :edit
    end
  end

  def destroy
    @league.destroy
    redirect_to leagues_path
  end

  private

  def league_params
    params.require(:league).permit(:user_id, :name)
  end
end

app/views/leagues/_form.html.erb
<div class="form-container">
  <div class="small-form">
    <h3 class="small-form-title"><%= label_text %></h3>
    <%= form_with(model: league, local: true) do |form| %>
      <% if league.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(league.errors.count, "error") %> prohibited this league from being saved:</h2>

          <ul>
          <% league.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name, 'League Name' %>
        <%= form.text_field :name, id: :league_name %>
      </div>

      <div class="actions">
        <%= form.submit button_text, class: 'button hollow small expanded' %>
      </div>
    <% end %>
  </div>
</div>

app/views/leagues/edit.html.erb
<%= render 'form', league: @league, label_text: 'Edit League', button_text: 'Update League' %>

app/views/leagues/index.html.erb
<div class="card-container">
  <div class="small-card">
    <div class="card">
      <div class="card-divider">
        <div class="card-main-section">
          <h3 class="league-index-title">Leagues</h3>
        </div>
        <% if @leagues.any? %>
          <%= link_to 'Create New League', new_league_path, class: 'button hollow tiny' %>
        <% end %>
      </div>
      <% if @leagues.empty? %>
        <div class="card-section league-card-section">
          <div>
            There are no leagues. Please <%= link_to 'add one', new_league_path %>.
          </div>
        </div>
      <% else %>
        <% @leagues.each do |league| %>
          <div class="card-section league-card-section">
            <%= link_to league.name, league_path(league) %>
            <div class="card-actions">
              <%= link_to edit_league_path(league), class: 'edit-icon' do %>
                <%= fa_icon 'edit' %>
              <% end %>
              <%= button_to league_path(league), { class: 'close-icon', form_class: 'inline-button-to', method: :delete } do %>
                <%= fa_icon 'times' %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/leagues/new.html.erb
<%= render 'form', league: @league, label_text: 'Create New League', button_text: 'Create League' %>

app/views/leagues/show.html.erb
<div class="card-container">
  <div class="card">
    <div class="card-divider">
      <div class="card-main-section">
        <h3 class="small-form-title"><%= @league.name %></h3>
        <small class="muted-text">League Owner: <%= @league.creator_full_name %></small>
      </div>
      <div class="card-header-actions">
        <%= link_to edit_league_path do %>
          <%= fa_icon 'edit 2x' %>
        <% end %>
      </div>
    </div>
    <div class="card-section league-card-section">

      <div class="small-nested-card">
        <%= render partial: 'shared/season_standings' %>
      </div>

      <div class="small-nested-card">
        <%= render partial: 'shared/games' %>
      </div>

      <div class="small-nested-card">
        <%= render partial: 'shared/seasons' %>
      </div>

    </div>
  </div>
</div>