config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'
  resources :leagues do
    resources :seasons do
      resources :games do
        resources :players do
          resource :finish, only: [:update]
        end
        resource :game_over, only: [:update]
      end
      resource :activate, only: [:update]
      resource :complete, only: [:update]
    end
  end
end

app/views/shared/_game.html.erb
<div class="card-section league-card-section">
	<div>
    <h6 class="small-form-title">
      <%= link_to "Game ##{game.number_in_order}", league_season_game_path(@league, game.season, game) %> - <%= game.date %>
    </h6>
    <small class="muted-text">Season #<%= game.season.number_in_order %></small>
    <br /><small class="muted-text">Winner: <%= game.winner_full_name %></small>
	</div>
</div>

app/views/shared/_games.html.erb
<div class="card">
  <div class="card-divider">
		<div class="card-main-section">
			<h4 class="small-form-title">Recent Games</h4>
		</div>
    <% if @league.active_season && can?(:manage, @league) %>
      <%= link_to 'Schedule New Game', new_league_season_game_path(@league, @league.active_season), class: 'button hollow tiny create-button' %>
    <% end %>
	</div>
	<% if @league.games.any? %>
    <%= render partial: 'shared/game', collection: @league.games.reverse_chronological.first(10) %>
	<% else %>
		<div class="card-section league-card-section">
      <section>
        There are no games. Please <%= link_to 'schedule one', new_league_season_game_path(@league, @league.active_season) %>.
      </section>
		</div>
	<% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="example-menu">
  <div class="grid-container">
    <div class="grid-x">
      <div class="top-bar-left">
        <ul class="menu" >
          <li class="menu-text site-title">Poker<span>Rank<span></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="dropdown menu" data-dropdown-menu>
					<% if !current_user %>
						<li class="nav-link"><%= link_to 'Sign Up', new_user_registration_path %></li>
						<li class="nav-link"><%= link_to 'Log In', new_user_session_path %></li>
					<% else %>
          <li>
            <a href="#" class="nav-link"><%= current_user.email %></a>
            <ul class="menu vertical">
              <li class="nav-link">
                <%= link_to 'Leagues', leagues_path %>
              </li>
              <li class="nav-link">
                <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
					<% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_season.html.erb
<div class="card-section league-card-section">
  <div>
    <h6 class="small-form-title">
      <%= link_to "Season ##{season.number_in_order}", league_season_path(@league, season) %>
    </h6>
    <small class="muted-text"># of Games: <%= season.games_count %></small>
    <br /><small class="muted-text">Season Leader: <%= season.winner_full_name %></small>
  </div>
  <section>
    <small>
      <%= season.active_text %>
      <%= button_to league_season_activate_path(@league, season), { class: 'activate-button', form_class: 'inline-button-to', method: :patch, title: season.active_title } do %>
        <%= fa_icon season.activate_button('active') %>
      <% end %>
    </small><br />
    <small>
      <%= season.completed_text %>
      <%= button_to league_season_complete_path(@league, season), { class: 'activate-button', form_class: 'inline-button-to', method: :patch, title: season.completed_title } do %>
        <%= fa_icon season.activate_button('completed') %>
      <% end %>
    </small>
  </section>
</div>

app/views/shared/_season_standings.html.erb
<div class="card">
  <div class="card-divider">
    <div class="card-main-section">
      <h4 class="small-form-title">Season Standings</h4>
    </div>
  </div>
  <%= render partial: 'shared/standing', collection: @league.active_season_standings %>
</div>

app/views/shared/_seasons.html.erb
<div class="card">
  <div class="card-divider">
    <div class="card-main-section">
      <h4 class="small-form-title">Seasons</h4>
    </div>
    <%= button_to 'Create New Season', league_seasons_path(@league), { class: 'button hollow tiny create-button', method: :post, params: { season: { league_id: @league.id } } } %>
  </div>
  <%= render partial: 'shared/season', collection: @league.seasons.reverse_order %>
</div>

app/views/shared/_standing.html.erb
<div class="card-section league-card-section">
	<div>
		<h6 class="small-form-title">
      <%= "#{(standing_counter + 1).to_i}. #{standing.user.full_name}" %>
		</h6>
    <small class="muted-text">Score: <%= standing.cumulative_score %></small>
    <br /><small class="muted-text">Games Played: <%= standing.games_count %></small>
	</div>
</div>