config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'
  resources :leagues do
    resources :seasons do
      resources :games do
        resources :players do
          resource :finish, only: [:update]
        end
        resource :game_over, only: [:update]
      end
      resource :activate, only: [:update]
      resource :complete, only: [:update]
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :season
  has_many :players
  delegate :league, to: :season

  validates :season_id, presence: true
  validates :date, presence: true

  scope :reverse_chronological, -> { order(date: :desc) }
  scope :chronological, -> { order(date: :asc) }

  def available_users
    users = User.joins(:permissions).where(permissions: { subject_class: 'League', subject_id: league.id }).sort_by(&:full_name) - players.map(&:user)
    users.collect { |user| [user.full_name, user.id] }
  end

  def blank_text
    available_users.empty? ? 'No players available' : 'Select a player'
  end

  def finish_all_players
    ordered_players = players.where.not(finishing_time: nil).order(finishing_time: :desc)
    ordered_players.each_with_index do |player, index|
      place = (index + 1).to_i
      player.update(finishing_place: place, score: player.calculate_score(place))
    end
  end

  def finished_players
    players.where.not(finishing_time: nil, id: nil).order(finishing_time: :desc)
  end

  def finished_players_count
    finished_players.count
  end

  def formatted_date
    date.strftime('%B %-e, %Y')
  end

  def number_in_order
    (league.games.chronological.index(self) + 1).to_i
  end

  def unfinish_all_players
    players.update_all(finishing_place: nil, score: nil)
  end

  def unfinished_players
    players.where(finishing_time: nil).where.not(id: nil)
  end

  def winner_full_name
    winner&.full_name
  end

  private

  def winner
    players.min_by(&:finishing_place)&.user
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  load_and_authorize_resource :league
  load_and_authorize_resource :season, through: :league
  load_and_authorize_resource :game, through: :season

  def index
  end

  def show
    @player = @game.players.new
  end

  def new
  end

  def edit
  end

  def create
    check_season_id
    if @game.save
      redirect_to league_season_game_path(@league, @season, @game)
    else
      render :new
    end
  end

  def update
    if @game.update(game_params)
      redirect_to league_season_game_path(@league, @season, @game)
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to league_season_games_path(@league, @season)
  end

  private

  def check_season_id
    if game_params['season_id'] && game_params['season_id'] != @game.season_id
      @season = Season.find(game_params['season_id'])
      @game.season_id = game_params['season_id']
    end
  end

  def game_params
    params.require(:game).permit(:season_id, :date, :completed)
  end
end

app/views/games/_finished_players.html.erb
<h3 class="small-form-title">Finished Players</h3>
<% if @game.finished_players.empty? %>
  <p>There are no finished players.</p>
<% else %>
  <ul class="accordion" data-accordion>
    <% @game.finished_players.each do |player| %>
    <li class="accordion-item is-active" data-accordion-item>
      <div class="accordion-content" data-tab-content>
        <div>
          <h6 class="small-form-title"><%= player.user_full_name %><%= " - #{player.finishing_place.ordinalize}" if player.finishing_place %></h6>
          <small class="muted-text">Rebuys or Add-ons: <%= number_to_currency(player.additional_expense) %></small><br />
          <% if player.score %>
            <small class="muted-text">Score: <%= player.score %></small><br />
          <% end %>
          <small class="muted-text">Finished at: <%= player.finished_at %></small>
        </div>
        <div>
          <% unless @game.completed? %>
          <%= button_to league_season_game_player_finish_path(@league, @season, @game, player), { class: 'close-icon', form_class: 'inline-button-to', method: :patch, params: { unfinish: true } }  do %>
            <%= fa_icon player.finishing_time ? 'thumbs-down' : 'check' %>
          <% end %>
          <%= button_to league_season_game_player_path(@league, @season, @game, player), { class: 'close-icon', form_class: 'inline-button-to', method: :delete } do %>
            <%= fa_icon 'times' %>
          <% end %>
        <% end %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>

<% end %>

app/views/games/_form.html.erb
<div class="form-container">
  <div class="small-form">
    <h3 class="small-form-title"><%= label_text %></h3>
    <%= form_for [@league, @season, @game] do |form| %>
      <% if game.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

          <ul>
          <% game.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :season_id %>
        <%= form.text_field :season_id, id: :game_season_id %>
      </div>

      <div class="field date-field">
        <%= form.label :date %>
        <%= form.date_select :date, id: :game_date %>
      </div>

      <div class="field">
        <%= form.check_box :completed, id: :game_completed %>
        <%= form.label :completed %>
      </div>

      <div class="actions">
        <%= form.submit button_text, class: 'button hollow small expanded' %>
      </div>
    <% end %>
  </div>
</div>

app/views/games/_game_header.html.erb
<div class="card-main-section">
  <h3 class="small-form-title">Game #<%= @game.number_in_order %></h3>
  <small class="muted-text"><%= @game.formatted_date %></small>
</div>
<div class="card-header-actions">
  <%= button_to league_season_game_game_over_path(@league, @season, @game), { class: 'close-icon', form_class: 'inline-button-to', method: :patch, params: { uncomplete: @game.completed? } } do %>
    <%= fa_icon @game.completed? ? 'times 2x' : 'table 2x' %>
  <% end %>
  <% unless @game.completed? %>
    <%= link_to edit_league_season_game_path(@league, @season, @game) do %>
      <%= fa_icon 'edit 2x' %>
    <% end %>
  <% end %>
</div>

app/views/games/_new_player_form.html.erb
<div class="nested-form">
  <h3 class="small-form-title">New Player</h3>
  <%= form_for [@league, @season, @game, @player] do |f| %>
    <%= f.label :user_id, 'Player' %>
    <%= f.select :user_id, @game.available_users, include_blank: @game.blank_text %>
    <small><a data-open="exampleModal1">Create a new user</a></small>
    <%= f.label :additional_expense %>
    <%= f.number_field :additional_expense %>
    <%= f.submit 'Just Save', class: 'button hollow small expanded', disabled: @game.completed? %>
    <%= f.submit 'Save & Finish', class: 'button hollow small expanded', disabled: @game.completed? %>
  <% end %>
</div>

app/views/games/_new_user_modal.html.erb
<div class="reveal" id="exampleModal1" data-reveal>
  <h1>Awesome. I Have It.</h1>
  <p class="lead">Your couch. It is mine.</p>
  <p>I'm a cool paragraph that lives inside of an even cooler modal. Wins!</p>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/games/_unfinished_players.html.erb
<h3 class="small-form-title">Unfinished Players</h3>
<% if @game.unfinished_players.empty? %>
  <p>There are no unfinished players.</p>
<% else %>
  <ul class="accordion" data-accordion>
    <% @game.unfinished_players.each do |player| %>
    <li class="accordion-item is-active" data-accordion-item>
      <div class="accordion-content" data-tab-content>
        <div>
          <small class="small-form-title"><%= player.user_full_name %></small><br />
          <small class="muted-text">Rebuys or Add-ons: <%= number_to_currency(player.additional_expense) %></small>
        </div>
        <div>
          <% unless @game.completed? %>
          <%= button_to league_season_game_player_finish_path(@league, @season, @game, player), { class: 'close-icon', form_class: 'inline-button-to', method: :patch, params: { unfinish: false } } do %>
            <%= fa_icon player.finishing_time ? 'thumbs-down' : 'check' %>
          <% end %>
          <%= button_to league_season_game_player_path(@league, @season, @game, player), { class: 'close-icon', form_class: 'inline-button-to', method: :delete } do %>
            <%= fa_icon 'times' %>
          <% end %>
          <% end %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
<% end %>

app/views/games/edit.html.erb
<%= render 'form', game: @game, label_text: 'Edit Game', button_text: 'Update Game' %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Season</th>
      <th>Date</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.season %></td>
        <td><%= game.date %></td>
        <td><%= game.completed %></td>
        <td><%= link_to 'Show', league_season_game_path(@league, @season, game) %></td>
        <td><%= link_to 'Edit', edit_league_season_game_path(@league, @season, game) %></td>
        <td><%= link_to 'Destroy', league_season_game_path(@league, @season, game), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_league_season_game_path(@league, @season) %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game, label_text: 'Schedule New Game', button_text: 'Schedule Game' %>

<%= link_to 'Back', league_season_games_path(@league, @season) %>

app/views/games/show.html.erb
<div class="card-container">
  <div class="card">
    <div class="card-divider">
      <%= render partial: 'game_header' %>
    </div>
    <div class="card-section game-card-section">
      <div class="form-container new-player-form">
        <%= render partial: 'new_player_form' %>
      </div>
      <div class="form-container player-list">
        <div class="nested-list">
          <%= render partial: 'finished_players' %>
          <%= render partial: 'unfinished_players' %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'new_user_modal' %>