config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'
  resources :leagues do
    resources :seasons do
      resources :games do
        resources :players do
          resource :finish, only: [:update]
        end
        resource :game_over, only: [:update]
      end
      resource :activate, only: [:update]
      resource :complete, only: [:update]
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  belongs_to :user
  delegate :season, to: :game

  validates :game_id, presence: true
  validates :user_id, presence: true, uniqueness: { scope: :game_id }

  delegate :full_name, to: :user, prefix: true, allow_nil: true
  delegate :finished_players_count, :buy_in, to: :game, prefix: true, allow_nil: true

  def calculate_score(place=nil)
    place = finishing_place if place.nil?
    numerator = game_finished_players_count * game_buy_in ** 2 / total_expense
    denominator = place + 1
    ((Math.sqrt(numerator) / denominator) * 100).floor / 100.0
  end

  def finished_at
    finishing_time.strftime('%I:%M %P on %B %-e, %Y')
  end

  def score_and_destroy
    destroy
    game.finish_all_players
  end

  def score_and_update(time=nil)
    update(finishing_time: time)
    game.finish_all_players
  end

  def self.rank_by_score(season=nil)
    @active_season = season || Season.last
    @season_users = select(:user_id).distinct.pluck(:user_id)
    return if @season_users.empty?

    find_by_sql(query)
  end

  private

  def self.query
    "SELECT user_id, SUM(score) AS cumulative_score, COUNT(game_id) \
     AS games_count FROM (#{subquery}) AS c_players GROUP BY \
     c_players.user_id ORDER BY cumulative_score DESC"
  end

  def self.subquery
    # TODO: (2018-04-26) markmiranda => LIMIT 9 needs to change to a season setting
    @season_users.map do |user_id|
      "(SELECT players.* FROM players INNER JOIN games ON \
       players.game_id = games.id WHERE user_id = #{user_id} AND \
       games.season_id = #{@active_season.id} ORDER BY score LIMIT 9)"
    end.join("\nUNION ALL\n")
  end

  def total_expense
    game_buy_in + additional_expense
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  load_and_authorize_resource :league
  load_and_authorize_resource :season, through: :league
  load_and_authorize_resource :game, through: :season
  load_and_authorize_resource :player, through: :game

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if params['commit'] == 'Just Save'
      @player.save
    else
      @player.score_and_update(Time.zone.now)
      @player.save
    end
    redirect_to league_season_game_path(@league, @season, @game)
  end

  def update
    if @player.update(player_params)
      redirect_to league_season_game_player_path(@league, @season, @game, @player)
    else
      render :edit
    end
  end

  def destroy
    @player.score_and_destroy
    redirect_to league_season_game_path(@league, @season, @game)
  end

  private

  def player_params
    params.require(:player).permit(:game_id, :user_id, :finishing_place, :score, :additional_expense)
  end
end

app/views/players/_form.html.erb
<div class="form-container">
  <div class="small-form">
    <h3 class="small-form-title">New player for Game</h3>
    <%= form_for [@league, @season, @game, @player] do |form| %>
      <% if player.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

          <ul>
          <% player.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :user_id %>
        <%= form.select :user_id, @game.available_users, include_blank: 'Select a User' %>
      </div>

      <div class="field">
        <%= form.label :additional_expense %>
        <%= form.text_field :additional_expense %>
      </div>

      <div class="actions">
        <%= form.submit 'Save Player', class: 'button hollow small expanded' %>
        <%= form.submit 'Save & Finish Player', class: 'button hollow small expanded' %>
      </div>
    <% end %>
  </div>
</div>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>User</th>
      <th>Finishing place</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.game %></td>
        <td><%= player.user %></td>
        <td><%= player.finishing_place %></td>
        <td><%= player.score %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<%= render 'form', player: @player %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @player.game %>
</p>

<p>
  <strong>User:</strong>
  <%= @player.user %>
</p>

<p>
  <strong>Finishing place:</strong>
  <%= @player.finishing_place %>
</p>

<p>
  <strong>Score:</strong>
  <%= @player.score %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>